src/rblmonitor/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views

import profiles.urls
import accounts.urls
import rbls.urls

urlpatterns = [
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^about/$', views.AboutPage.as_view(), name='about'),
    url(r'^rbls/', include(rbls.urls, namespace='rbls')),
    url(r'^users/', include(profiles.urls, namespace='profiles')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include(accounts.urls, namespace='accounts')),
]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Include django debug toolbar if DEBUG is on
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

src/rbls/urls.py
from django.conf.urls import url
from . import views

app_name = 'urls'

urlpatterns = [
    url(r'^list$', views.RBLView.as_view(), name='list'),
    url(r'^check$', views.RBLCheck.as_view(), name='check'),
]

src/rbls/models.py
from django.db import models

class Rbllist(models.Model):
    name = models.CharField(max_length=100)
    url = models.URLField(max_length=100, unique=True)
    description = models.CharField(max_length=300, null=True, blank=True)

    # def __str__(self):
    #     return self.name

src/rbls/forms.py
from django import forms
from .models import Rbllist

class AddrForm(forms.Form):
    address = forms.GenericIPAddressField(label='IPv4 or IPv6 Address ')

    def clean_address(self):
        address = self.cleaned_data['address'] 
        return address

src/rbls/views.py
from django.shortcuts import render
from django.template import loader
from django.views import generic
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect

from rbls.forms import AddrForm
from rbls.models import Rbllist
from rbls.bin.blcheck import _ipstatus

rbls = Rbllist.objects.values_list('name', flat=True)
bls_url = Rbllist.objects.values_list('url', flat=True)


class RBLView(generic.TemplateView):
    template_name = 'rbl_list.html'

    def get(self, request):
        addrform = AddrForm()
        data = { 'rbls': rbls, 'form': addrform }
        return render(request, self.template_name, data)

class RBLCheck(generic.TemplateView):
    template_name = 'rbl_check.html'

    def get(self, request):
        check = []
        if request.method == 'GET':
            addrform = AddrForm(request.GET)
        if addrform.is_valid():
            address = addrform.cleaned_data['address']

            for bl in bls_url:
                check.append(_ipstatus(address, bl))
            data = {
                'bls': bls_url,
                'address': address,
                'check': check,
            }
            return render(request, self.template_name, data)

        else:
            addrform = AddrForm()
            return HttpResponseRedirect('/rbls/list')

        return HttpResponseRedirect('/rbls/list')

src/rbls/templates/rbl_check.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Rbl Check{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="about" %}
{% endblock %}

<!-- Benefits of the Django application -->
{% block container %}

<div id="sec2" class="text-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1>{% include "_brandname.html" %}</h1>
        <p class="lead">Blacklist address result for {{ address }}</p>
        <ul>
          {% for c in check %}
            {% if c.state %}
                <li>Is LISTED in {{ c.bl }}. Result: {{ c.txt }}, {{ c.a }} </li>
            {% else %}
                <li>Is NOT LISTED in {{ c.bl }}</li>
            {% endif %}
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
</div>

{% endblock container %}

src/rbls/templates/rbl_list.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Rbl List{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="about" %}
{% endblock %}

<!-- Benefits of the Django application -->
{% block container %}

<div id="sec1" class="text-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h2>Address check</h2>
        <form action="{% url 'rbls:check' %}" method="GET">
          {% csrf_token %}
          {{ form }}
          <input type="submit" value="OK">
        </form>
      </div>
    </div>
  </div>
</div>

<div id="sec2" class="text-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <p class="lead">Blacklists Status</p>
        <ul>
          {% for rbl in rbls %}
            <li>{{ rbl }}</li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
</div>

{% endblock container %}